spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 9010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka