spring:
  application:
    name: user-service
  datasource:
    url: ${USER_SERVICE_DATASOURCE_URL}
    username: ${USER_SERVICE_DATASOURCE_USERNAME}
    password: ${USER_SERVICE_DATASOURCE_PASSWORD}
    driver-class-name: ${USER_SERVICE_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 9030

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
springdoc:
  api-docs:
    path: /api-docs